name: flutter_fractal_onboarding_poc
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
